apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mydeploy-hpa
  namespace: ex6
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydeploy
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 90
          type: Utilization
