---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: nginx-admin
  namespace: ex6
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- nginx-context-user
allowedCapabilities:
- CHOWN
- SETUID
- SETGID